# QBit Task Environment Configuration File

robot:
  name: ur5e
  robot_config_path: /workspace/qbit/configs/robots/ur5e.yaml
  base_pose:
    position: [0.2, 0, 0.95]
    quaternion: [0, 0, 0, -1] # wxyz # TODO: Use the default base quaternion in xml, check and change this later


env_objects:
  - obj_name: table
    mesh_type: mesh # mesh / sphere / coacd
    mesh_path: /workspace/qbit/assets/task_env/lab_tables/tisch_neu_s0.obj
    attach_body: 'world'
    attach_pose:
      position: [0, -0.35, 0.15]
      quaternion: [ 0.5, 0.5, 0.5, 0.5 ]
    scale: [1, 1, 1]


task_objects:
  - obj_name: hole_female
    mesh_type: coacd # mesh / sphere / coacd
    mesh_path: /workspace/qbit/assets/task_env/peg_in_hole_simple/assets/simple_example_hole.obj
    attach_body: 'world'
    attach_pose:
      position: [-0.4, 0.0, 0.91]
      quaternion: [0.7071068, 0.7071068, 0, 0] # wxyz
    scale: [0.001, 0.001, 0.001]
    mass: 0.001
    material: normal
    mesh_color: [0.0, 1, 0.0, 0.8]
    contact:
      condim: 3
      friction: 0.5

  - obj_name: peg
    mesh_type: sphere # mesh / sphere / coacd
    mesh_path: qbit/assets/task_env/colored_objects/cylinder_with_ring_0.04/cylinder_with_ring_0.04.obj
    #/workspace/qbit/assets/task_env/peg_in_hole_simple/assets/simple_example_peg.obj
    attach_body: 'tool0'
    attach_pose:
      position: [0, 0, 0.11]
      quaternion: [1.0, 0.0, 0.0, 0.0] #[ 0.5, 0.5, 0.5, 0.5 ] # wxyz
    scale: [0.85, 0.85, 0.85] #[0.00095, 0.00095, 0.00095]
    mesh_color: [1, 0, 0, 1]
    material: normal
    mass: 0.001 # set the mass to 0.0001 to avoid the additional compensation (calibration)
    contact:
      condim: 3
      friction: 0.5