# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: qbit.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'qbit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nqbit.proto\x12\tqbit_grpc\"\x14\n\x04Ping\x12\x0c\n\x04ping\x18\x01 \x01(\x08\"\x14\n\x04Pong\x12\x0c\n\x04pong\x18\x01 \x01(\x08\".\n\x08ObsState\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x0e\n\x06wrench\x18\x02 \x03(\x01\"\x1f\n\tEEFAction\x12\x12\n\neef_action\x18\x01 \x03(\x01\"6\n\rArmJointState\x12\x11\n\tpositions\x18\x01 \x03(\x01\x12\x12\n\nvelocities\x18\x02 \x03(\x01\"#\n\x0e\x41rmJointPosCmd\x12\x11\n\tjoint_pos\x18\x01 \x03(\x01\"#\n\x0e\x41rmJointVelCmd\x12\x11\n\tjoint_vel\x18\x01 \x03(\x01\"i\n\rArmEEFPoseCmd\x12)\n\x0c\x65\x65\x66_position\x18\x01 \x01(\x0b\x32\x13.qbit_grpc.position\x12-\n\x0e\x65\x65\x66_quaternion\x18\x02 \x01(\x0b\x32\x15.qbit_grpc.quaternion\"+\n\x08position\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"&\n\x03rpy\x12\t\n\x01r\x18\x01 \x01(\x01\x12\t\n\x01p\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\"8\n\nquaternion\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\t\n\x01w\x18\x04 \x01(\x01\x32\xf1\x02\n\rQbitInterface\x12;\n\x15\x43heckServerConnection\x12\x0f.qbit_grpc.Ping\x1a\x0f.qbit_grpc.Pong\"\x00\x12L\n\x1dRequestNextActionForInsertion\x12\x13.qbit_grpc.ObsState\x1a\x14.qbit_grpc.EEFAction\"\x00\x12J\n\x11MoveArmToJointPos\x12\x19.qbit_grpc.ArmJointPosCmd\x1a\x18.qbit_grpc.ArmJointState\"\x00\x12H\n\x10MoveArmEEFtoPose\x12\x18.qbit_grpc.ArmEEFPoseCmd\x1a\x18.qbit_grpc.ArmJointState\"\x00\x12?\n\x10GetArmJointState\x12\x0f.qbit_grpc.Ping\x1a\x18.qbit_grpc.ArmJointState\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qbit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PING']._serialized_start=25
  _globals['_PING']._serialized_end=45
  _globals['_PONG']._serialized_start=47
  _globals['_PONG']._serialized_end=67
  _globals['_OBSSTATE']._serialized_start=69
  _globals['_OBSSTATE']._serialized_end=115
  _globals['_EEFACTION']._serialized_start=117
  _globals['_EEFACTION']._serialized_end=148
  _globals['_ARMJOINTSTATE']._serialized_start=150
  _globals['_ARMJOINTSTATE']._serialized_end=204
  _globals['_ARMJOINTPOSCMD']._serialized_start=206
  _globals['_ARMJOINTPOSCMD']._serialized_end=241
  _globals['_ARMJOINTVELCMD']._serialized_start=243
  _globals['_ARMJOINTVELCMD']._serialized_end=278
  _globals['_ARMEEFPOSECMD']._serialized_start=280
  _globals['_ARMEEFPOSECMD']._serialized_end=385
  _globals['_POSITION']._serialized_start=387
  _globals['_POSITION']._serialized_end=430
  _globals['_RPY']._serialized_start=432
  _globals['_RPY']._serialized_end=470
  _globals['_QUATERNION']._serialized_start=472
  _globals['_QUATERNION']._serialized_end=528
  _globals['_QBITINTERFACE']._serialized_start=531
  _globals['_QBITINTERFACE']._serialized_end=900
# @@protoc_insertion_point(module_scope)
