
robot_type: ur5e
mujoco_xml_path: /workspace/qbit/assets/robots/ur5e/scene.xml

joints:
  - shoulder_pan_joint
  - shoulder_lift_joint
  - elbow_joint
  - wrist_1_joint
  - wrist_2_joint
  - wrist_3_joint
initial_positions: [0, -1.57079632, 1.57079632, -1.57079632, -1.57079632, 0]
default_controller: joint_position_controller
goal_tolerance: 0.002

# ik
ik_solver: trackik
ik_description: /workspace/qbit/assets/robots/ur5e/ur5e_robot.urdf
ik_base_link: base
ik_eef_link: wrist_3_link


controllers:
  joint_position_controller:
    vel_max: [3.14, 3.14, 3.14, 3.14, 3.14, 3.14]
    kp: 2.0
    kd: 0.02
    control_loop: 0.001 # s
  
  eef_position_controller:
    vel_max: [0.4, 0.4, 0.4, 0.4, 0.4, 0.4]
    kp: [5, 5, 5, 2, 2, 2] # translation and rotation
    kd: [2, 2, 2, 0.2, 0.2, 0.2]
    control_loop: 0.001 # s
  
  eef_admittance_controller:
    vel_max: [0.1, 0.1, 0.1, 10, 10, 10]
    activation_mask: [1, 1, 1, 1, 1, 1]
